// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Test': typeof import("../../components/test.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
  }
}
export {}
